import { useMemo, useState } from 'react';
import { Check, ChevronRight, CircleAlert, RotateCcw, Save, ShieldCheck } from 'lucide-react';
import { Link } from 'wouter';
import { useFieldTest } from '@/hooks/use-field-test';
import { EvidenceLabel, Meter, SectionKicker } from '@/components/field-ui';

export default function Setup() {
  const { setup, toggleSetupItem, resetDemo } = useFieldTest();
  const [saved, setSaved] = useState(false);
  const complete = useMemo(() => setup.filter((item) => item.complete).length, [setup]);
  const groups = Array.from(new Set(setup.map((item) => item.group)));
  const markItem = (id: string) => {
    toggleSetupItem(id);
    setSaved(true);
    window.setTimeout(() => setSaved(false), 1800);
  };

  return (
    <div className="mx-auto max-w-[1160px]">
      <section className="fade-up flex flex-col justify-between gap-5 border-b border-[#cfd2c9] pb-7 md:flex-row md:items-end"><div><div className="mb-4 flex items-center gap-3"><SectionKicker>Owner setup / readiness</SectionKicker><EvidenceLabel /></div><h1 className="font-display text-3xl font-extrabold tracking-[-0.05em] sm:text-5xl">Make the next test repeatable.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#687271]">Fill the owner inputs before the field window. Measured items are deliberately separated from setup assumptions so the handoff has a clean boundary.</p></div><div className="flex items-center gap-2 text-xs text-[#687271]">{saved && <span className="inline-flex items-center gap-1 text-[#236047]"><Save size={13} /> Saved locally</span>}<button onClick={resetDemo} className="inline-flex items-center gap-2 border border-[#c6cbc3] bg-[#fbfbf7] px-3 py-2 font-bold hover:border-[#203c49]" data-testid="button-reset-setup"><RotateCcw size={14} /> Reset checklist</button></div></section>
      <section className="fade-up fade-up-1 mt-5 border border-[#d7d8d0] bg-[#203c49] p-5 text-[#f2f0e6] sm:p-6"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><SectionKicker>Readiness meter</SectionKicker><div className="mt-2 flex items-baseline gap-2"><span className="font-display text-4xl font-extrabold tracking-[-0.06em] text-[#ffd067]">{complete}</span><span className="font-mono-ui text-xs text-[#aec0b8]">/ {setup.length} ready</span></div><p className="mt-1 max-w-xl text-xs leading-5 text-[#aec0b8]">Owner setup is stored by the API. Completing an item does not mark its feasibility gate as verified.</p></div><div className="w-full sm:w-64"><div className="mb-2 flex justify-between font-mono-ui text-[10px] uppercase tracking-[0.12em] text-[#aec0b8]"><span>Checklist coverage</span><span>{Math.round((complete / setup.length) * 100)}%</span></div><Meter value={complete} total={setup.length} color="bg-[#ffd067]" /></div></div></section>
      {complete < setup.length && <div className="fade-up fade-up-2 mt-5 flex gap-3 border-l-2 border-[#e8a629] bg-[#fff8e7] px-5 py-4"><CircleAlert size={18} className="mt-0.5 shrink-0 text-[#a06712]" /><div><p className="text-sm font-bold text-[#765013]">Before the next window</p><p className="mt-1 text-xs leading-5 text-[#765013]">Confirm the shortcut path and test mode with the owner. SMS and WhatsApp are delivered by the handset itself; XMPP and email leave this console through their configured provider endpoints.</p></div></div>}
      <section className="fade-up fade-up-2 mt-5 space-y-5">
        {groups.map((group) => <div key={group} className="border border-[#d7d8d0] bg-[#fbfbf7]"><div className="flex items-center justify-between border-b border-[#d7d8d0] px-5 py-4"><div><SectionKicker>{group}</SectionKicker><h2 className="mt-1 font-display text-lg font-extrabold tracking-[-0.03em]">{group === 'Device surface' ? 'Device surface' : group === 'Connectivity' ? 'Connectivity inputs' : group === 'Entry path' ? 'Entry path' : 'Run control'}</h2></div><span className="font-mono-ui text-[10px] uppercase tracking-[0.1em] text-[#687271]">{setup.filter((item) => item.group === group && item.complete).length} / {setup.filter((item) => item.group === group).length}</span></div><div className="divide-y divide-[#e3e4dc]">{setup.filter((item) => item.group === group).map((item) => <div key={item.id} className="flex items-start gap-4 px-5 py-4 transition-colors hover:bg-[#f7f7f1]" data-testid={`row-setup-${item.id}`}><button onClick={() => markItem(item.id)} className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center border transition-colors ${item.complete ? 'border-[#236047] bg-[#236047] text-[#f2f0e6]' : 'border-[#9da9a3] bg-[#f7f7f1] text-transparent hover:border-[#a06712]'}`} aria-label={`${item.complete ? 'Unmark' : 'Mark'} ${item.label}`} data-testid={`button-toggle-setup-${item.id}`}><Check size={13} strokeWidth={3} /></button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`text-sm font-bold ${item.complete ? 'text-[#43575a]' : 'text-[#203c49]'}`}>{item.label}</p><span className={`font-mono-ui text-[9px] uppercase tracking-[0.1em] ${item.mode === 'measured' ? 'text-[#a06712]' : 'text-[#687271]'}`}>{item.mode === 'measured' ? 'measured' : 'owner input'}</span></div><p className="mt-1 max-w-2xl text-xs leading-5 text-[#687271]">{item.detail}</p></div><ChevronRight size={16} className="mt-1 shrink-0 text-[#b0b5ad]" /></div>)}</div></div>)}
      </section>
      <section className="fade-up fade-up-3 mt-5 grid gap-5 md:grid-cols-2"><div className="border border-[#d7d8d0] bg-[#fbfbf7] p-5"><div className="flex gap-3"><ShieldCheck size={19} className="mt-0.5 text-[#236047]" /><div><h2 className="font-display font-extrabold tracking-[-0.02em]">Ready to hand off?</h2><p className="mt-1 text-xs leading-5 text-[#687271]">Use the gates view to turn these owner inputs into explicit acceptance evidence. Keep the local checklist as a record of what was true before the run.</p><Link href="/gates" className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#a06712]" data-testid="link-setup-gates">Open gates <ChevronRight size={14} /></Link></div></div></div><div className="border border-[#d7d8d0] bg-[#f4f3ed] p-5"><h2 className="font-display font-extrabold tracking-[-0.02em]">Boundary note</h2><p className="mt-2 text-xs leading-5 text-[#687271]">This console does not infer cryptography, remote attacker behavior, app automation, or production guarantees. It only records the feasibility questions the owner can answer.</p></div></section>
    </div>
  );
}